SHELL := /bin/bash
.ONESHELL:
.SHELLFLAGS := -eu -c

JDK17_HOME := /usr/lib/jvm/java-17-openjdk-amd64
DCM4CHE_DIR := /workspaces/dcm4che
ASSEMBLY_TARGET := $(DCM4CHE_DIR)/dcm4che-assembly/target

.PHONY: all prereq java build unzip env clean help

all: prereq java build unzip env

help:
	@echo "make all   -> disable Yarn repo (if broken) + Java17 + build dcm4che bin + env.sh"
	@echo "source env.sh ; dcm2jpg -h"

# --- Fix apt-get update failures due to Yarn repo (NO_PUBKEY)
prereq:
	echo "[Prereq] Handling Yarn apt repo if it breaks apt-get update..."
	if [ -f /etc/apt/sources.list.d/yarn.list ]; then \
	  echo "  - Found /etc/apt/sources.list.d/yarn.list"; \
	  echo "  - Disabling it (commenting deb line)"; \
	  sudo sed -i 's/^[[:space:]]*deb /# deb /' /etc/apt/sources.list.d/yarn.list || true; \
	else \
	  echo "  - No yarn.list found, nothing to do."; \
	fi

java:
	echo "[Java] apt-get update..."
	sudo apt-get update
	echo "[Java] Installing OpenJDK 17..."
	sudo apt-get install -y openjdk-17-jdk unzip
	sudo update-alternatives --set java  $(JDK17_HOME)/bin/java || true
	sudo update-alternatives --set javac $(JDK17_HOME)/bin/javac || true
	export JAVA_HOME=$(JDK17_HOME)
	export PATH="$$JAVA_HOME/bin:/usr/bin:$$PATH"
	hash -r
	java -version
	javac -version

build:
	echo "[Build] Building dcm4che assembly..."
	cd $(DCM4CHE_DIR)
	export JAVA_HOME=$(JDK17_HOME)
	export PATH="$$JAVA_HOME/bin:/usr/bin:$$PATH"
	./mvnw -DskipTests install -pl dcm4che-assembly -am

unzip:
	echo "[Unzip] Extracting dcm4che distribution..."
	cd $(ASSEMBLY_TARGET)
	ZIP=$$(ls -1 dcm4che-*-bin.zip | head -n 1)
	unzip -o "$$ZIP" >/dev/null
	ls -d dcm4che-*/bin

env:
	echo "[Env] Generating env.sh..."
	BIN_DIR=$$(ls -d $(ASSEMBLY_TARGET)/dcm4che-*/bin | head -n 1)
	echo "# Auto-generated by Makefile" > env.sh
	echo "export DCM4CHE_BIN=\"$$BIN_DIR\"" >> env.sh
	echo "export PATH=\"\$$DCM4CHE_BIN:\$$PATH\"" >> env.sh
	echo "hash -r" >> env.sh
	chmod +x env.sh
	echo "✅ env.sh created. Run: source env.sh && dcm2jpg -h"

clean:
	rm -f env.sh
